### ISSUE TITLE
Missing some entities

### ISSUE THREAD

**Issue by aboodh95** [rajyraman/Metadata-Virtual-Entity#1]
Hi,

I'm having an issue that some entities are not showing, the first page will show you the count of all entities, once i go to the next page some entities will disappear

![image](https://user-images.githubusercontent.com/12459798/43444969-2fc65e80-94b6-11e8-882b-a25ad13db8a8.png)

![image](https://user-images.githubusercontent.com/12459798/43444992-3f2d177e-94b6-11e8-99e4-7a49c07395f2.png)

**Comment by rajyraman** [comment]
I will check this. I was able to reproduce this issue as well.

**Comment by rajyraman** [comment]
The latest release should fix this issue. Please try and let me know.
