### ISSUE TITLE
Need an unmanaged solution so I can extend it

### ISSUE THREAD

**Issue by dotfede** [rajyraman/Metadata-Virtual-Entity#2]
Hi. I'm willing to extend this project to support additional types such as SystemForm, View, etc.

I need an unmanaged solution that I can import, extend (add additional virtual entities) and then eventually export as managed.

**Comment by rajyraman** [comment]
@fberasategui - Added unmanaged solution to the release https://github.com/rajyraman/Metadata-Virtual-Entity/releases
